### ISSUE TITLE
RATING APPEAL - A-DEX BP GUILD

### ISSUE THREAD

**Issue by Avm07** [wax-office-of-inspector-general/waxguilds#1129]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. WAX Signals - New product was launched and announced, all current DEXes activities on WAX supported, no points granted. Why? Docs: https://docs.a-dex.io/products/signals
2. AA API - We dont have any issues on our end on 10/10 date. We contacted failed validators, no HTTP requests, responces, error codes, error messages were provided. So we are considered they are ddosing our services and got rate limited. Ledgerwise and BetterStack show no issues at all, again there is no down time on 10/10. Links:
https://nodestatus.ledgerwise.io/wax/producer/bp.adex?tab=charts
https://status.a-dex.io

Thank you

**Comment by kaefergeneral** [comment]
Hello @Avm07,

1.) We evaluate based on multiple criteria. WAX Signals does not satisfy any of them, so we do not consider it point-worthy. Your channel currently has 15 subscribers, but nobody is looking at the feed. Whenever we checked it, the view count was 1 or 2, depending on the count of IGs reviewing the information. When we reviewed the published data, we also noticed considerable delays in trades being published, while significant numbers of transactions were missing from the feed. We have similar channels that share all NFT sales in a similar manner. Those do not receive points either. If it were a bot that allowed you to define what data you get, it could be considered useful. And if it then gained some traction, we could consider it for points.

2.) As per validationcore for the evaluated timeframe, you have an uptime of 86.23%; validationcore confirms the same, stating an uptime of 87% with a multi-day downtime from the 9th to 11th of October. Both report timeouts / invalid responses in the given timeframe, trying to request any data beyond a health check. The issues have since been resolved and if there are no additional downtimes, the points will be granted with the next infrastructure evaluation.

Best regards
your OIG
