### ISSUE TITLE
RATING APPEAL - Detroit Ledger Tech

### ISSUE THREAD

**Issue by eosiodetroit-adam** [wax-office-of-inspector-general/waxguilds#1130]
Good Day IG's

Can you please reconsider the points awarded/not awarded for the following:

1. FACINGS Studio - An additional video that was provided via email to the IGs was not viewed based on analytics from Youtube and I don't believe this properly evaluated. I did see after I DM'd Jannis about this a few days ago there were some longer views. We obviously don't expect each of you to sit down and watch the whole video but was surprised to see it not viewed at all as it was the primary update. The video generally covers importing and syncing existing collections into FACINGS (6:30), Create a pack/pack odds (9:40), Publishing to chain from draft (10:10), Bulk importing from delimited files (11:00), Creating sales and payment processing (12:20), Users/roles (19:00), Results of Dark Pinup full sync (21:00), Q/A from team (23:00). This was used to successfully launch Pantheon a few weeks after this video was recorded.

2. WAX Labs - Despite working with the WAX team to advise/determine a game plan for deployment issues and optimization (due to their initial preferred setup), fixing high priority issues/refactors (and asking for help confirming as we don't have admin/mod access), and asking to determine some sort of expectations around product support for WL we have not received any proactive feedback if issues are fixed, etc.

If this was left off due to having too many product development items, we feel that it qualifies for ecosystem points given that the nature of the product is to attract and facilitate the development of new products, tools, and codebases that can be leveraged by the community. The code is now fully open sourced in the correct repo that belongs to WAX, and Labs is not something that DLT can actually monetize outside of the contract development work we did or implement into a scalable business strategy. Surely this is worth something to community if there are telegram bots that routinely being awarded at least 1 point.

Thank you,
Adam

**Comment by rakeden** [comment]
Good Day Adam,

after a thorough internal debate we do believe that we should meet and discuss those two contributions in particular, and how to handle them going forward.

1. Based on your submission, we had already decided to uphold the score for FACINGS Studio until January, this is now also properly reflected by the decay date. It is true, that the video was not watched during our intial review period. But this does not mean, that your submission was not properly reviewed. Your written report was already sufficient for our decision to uphold the score. Given that, at the time of review, the potential release date was at least 2~3 months out, the contents of the video would not, and after watching, did not, impact the current review beyond ensuring us that you are making progress. 
As soon as Pantheon is officially reported as out of development and you have a more precise release date, we will be able to re-evaluate and increase the score for this contribution based on the contents of the video and what ever you might report until then. Otherwise you can of course expect a score increase when the product launches successfully.

2. We do see your effort on the github repository, thanks. We also still do consider most of what is being worked on as part of the missing features from the labs proposal earlier last year, for which you have been granted points for an entire year, in addtion to being compensated through WAX Labs. However, we want to work out a feasible frame for the future, so that we can go forward with you contributing and us rewarding your effort. 

It's important that we meet shortly and discuss the details of such an agreement, as we wish for a few new features on WAX labs to be added soon.

Please don't feel discouraged to continue issuing a report whenever you complete a feature or carry out a significant amount of work. Ultimately we want to progress this project with distinct planning security, which you probably also want.

Keep in mind, that you can already submit an update for your progress on Pantheon and its launch until end of next week, that would be reflected in score update in the following week.


kind regards,
OIG
