### ISSUE TITLE
Sentnlagents - October 2021 appeal

### ISSUE THREAD

**Issue by ankh2054** [wax-office-of-inspector-general/waxguilds#137]
Hi OIG,

**Products:**

-  Last month our products EOS monitor product & OIG portal products got a multiplier of 3, but this month they only got 2. Wondering whether that is an error or there is reasoning we should know about.

**Use API:**

- On the scoring for Atomic Assets, I wondering whether a multiplier score of 2 is possible, due to providing the CVE API which was previously given a score of 1 and now also providing Atomic API.

**Score:**

- And lastly my score is actually 172 according to the report. 

Thanks for all your hardwork as always.

thanks
Charles

**Comment by rakeden** [comment]
Hi Sentnlagents,

thanks for the appeal. Here is our feedback:

**Products**
In the past month there hasn't been updates committed for the OIG tool - As long as we don't see progress we can't grant points for the products, so it started decaying until an update is provided. The same accounts for eosmonitor, which doesn't have regular updates. 
We suggest you start providing usage metrics to us so that we can see that a tool is needed, used and developed over time.

**Use API**
We deducted a point for the CVE API, because the last added CVE is from July. Unless the tool is updated and the update is explained in the report we can't grant a point for it. Also for anything regarding APIs the Usage metrics should be disclosed.

**Score**
We deducted 10 penalty points for missing the secondary requirement.
"99.5% Round availability by WAX mainnet data, or testnet data if mainnet is not available. (10 Point Penalty if missed)"

**Comment by ankh2054** [comment]
Thanks for the clarification all makes sense. Only thing is mention is that EOS monitor did have an update this month.

**Comment by rakeden** [comment]
EOS Monitor got an initial score boost on release but is essentially considered a community tool due to the limit complexity, hence the points decaying.

So ultimately this means:
EOS Monitor decays to 2 points in Oct'21, Nov'21 to 1 point, then in December to "community tools".
