### ISSUE TITLE
Ledgerwise February Appeal 

### ISSUE THREAD

**Issue by Tanishv** [wax-office-of-inspector-general/waxguilds#261]
Hello IGs, 

1. We are running and maintaining Testnet history - https://waxtestnet.ledgerwise.io/v2/health

2. We wish to understand why we didn't get any points for Hindi translations and waxhindi website in engagement. 

Apart from Appeal - 

1. We are upgrading to better machines for better performance and reliability and two of our backups are currently syncing. One will be up by Tomorrow i.e. 13th March. For the last month we were dependent on our third backup, we know that our services are currently missing blocks, but that's a trade-off we have to make for providing better service to the community. Hopefully you won't find any complains related to missing blocks from next technical or general evaluation.

2. We could add testnet to tools.ledgerwise.io which could check and information related to guilds testnet nodes including Testnet history. 

Thank you.

**Comment by rakeden** [comment]
Hello @Tanishv 

we've revisited your rating based on your appeal and made the following adjustments:

1. Add 1 point for testnet-history solution
2. Add 1 point for hindi translations as ecosystem contribution
3. Remove 1 point from mainnet-history, because v2 was not usable after 23-02-2022

Also: We'd love to have a tool like tools.ledgerwise.io for testnet monitoring. Please consider a future submission in the category `product-development`.

Cheers,
