### ISSUE TITLE
WeCan guild - Jul 2022 Appeal

### ISSUE THREAD

**Issue by We-Can-dev** [wax-office-of-inspector-general/waxguilds#391]
Dear OIGs,

We would like to ask you to reconsider the evaluation for a couple of our services and interactions.

1. Our backup service (https://backup.wecan.dev/) provides full WAX ecosystem backups with most recent history and it was evaluated at 18 points for Atomic Assets and WAX backups, though our Hyperion ES snapshots (https://backup.wecan.dev/wax/hyperion/mainnet/, https://backup.wecan.dev/wax/hyperion/testnet/) were omitted for some reason, despite that we included it in our report for July.
We would like to receive additional points for this service as the other guilds did.

2. Our ecosystem tool blockchain explorer (https://waxscan.wecan.dev/) which we provide free of charge still gets 12 points, despite it having more functionality of block exploring than some of the existing tools which are either being paid for or being evaluated much higher. We want to ask you to do a secondary review of it's functionality (which we pointed out in the report) and it's performance and provide additional points for this service which is being more complex than just another monitoring tool (and some guilds receive tremendous amount of points for them) and is in active development right now but in parallel has full functionality for block exploring.

3. We helped to successfully start https://miningnetwork.io/ which was very warmly received by the WAX community which can be seen by the amount of youtube videos in different languages https://www.youtube.com/results?search_query=miningnetwork with lots of views, the Dappradar stats https://dappradar.com/wax/games/miningnetwork, NFTHive stats https://nfthive.io/collections/p2e/miningntwrkc, Atomichub stats https://wax.atomichub.io/explorer/collection/miningntwrkc, and the volume of interaction for the token https://alcor.exchange/trade/btk-miningntwrkt_wax-eosio.token.
To clarify, this is not a staking system and this game doesn't have staking system as is. This is purely mining simulator which has been gamified to p2e model with internal minigames.
We want to ask you to reconsider the evaluation for helping to bring this project to WAX and provide additional points, taking into account that other guilds received more points for bringing less popular projects which are at the same level of complexity and use similar economic model.

Kind regards, 
WeCan.dev team.

**Comment by kaefergeneral** [comment]
Hi WeCan.dev team,

1.) You are getting the same points other guilds are getting for providing the Hyperion and AA Snapshots.

2.) We really like the performance of waxscan, but as no usage metrics were provided, the site is not very user firendly and has bugs, we considered it as in development and scored as such.

3.) Miningnetwork has been on WAX for multiple months and you have been recieving a score for it accordingly. At this stage we see no reason to increase the score.

Best whishes,
your IGs

**Comment by We-Can-dev** [comment]
@kaefergeneral

**Comment by We-Can-dev** [comment]
>1.) You are getting the same points other guilds are getting for providing the Hyperion and AA Snapshots.

This is incorrect.
Please review again
https://ibb.co/fpj3zYP

**Comment by We-Can-dev** [comment]
@kaefergeneral 
>3.) Miningnetwork has been on WAX for multiple months and you have been recieving a score for it accordingly. At this stage we see no reason to increase the score.

This is also not exactly true, because we received points when this product was in development and it wasn't evaluated when it wen't into full public usage in June.
We've stated this in our report as well.

**Comment by We-Can-dev** [comment]
>2.) We really like the performance of waxscan, but as no usage metrics were provided, the site is not very user firendly and has bugs, we considered it as in development and scored as such.

This is rough data only for the 7 last days https://ibb.co/tDjZ8wY because we didn't add it for google analitycs yet, but it's just for the perspective.

**Comment by kaefergeneral** [comment]
1. You got the same score as other guilds simply providing snapshots.
The example you picked got more points because they are providing more than snapshots.
They have a maintained support channel and extensive guides on how to use their snapshots.

2. We will revisit waxscan on the next evaluation if proper metrics are provided before the cut-off date.
Our concerns mentioned above do remain though.

3. The scoring is based on the involvement of the guild in the project. As per your report you are providing consultation and audits. This is generally given a score of 1. The ecosystem impact and popularity of a project determines for how long you will score the points until it decays. While there can be a point increase, upon release of a project, we did not see it warranted.
For your comparison to Coin Pirates, as mentioned above scores are awarded based on involvement. As per the reports cryptolions has not only been consulting but actively developing said project, supplying them with, and maintaing their smart contracts. This is scored differently. But we appreciate the highlight. We will also revisit their score as it seems there might have been a lack of decay and the current score is higher than it should be. Then again, Coin Pirates had almost double the total NFT trade volume  (USD based) miningnetwork currently has.
