### ISSUE TITLE
EOSphere Guild - September 2022 Appeal

### ISSUE THREAD

**Issue by Rossco99** [wax-office-of-inspector-general/waxguilds#432]
Good Day IG's

Would you mind looking into the following two queries:

Engagement 1 - Typically we have received 3/5 points for our comprehensive Snapshot Library Support and Education, however this month we have only received 2/5 points?

Engagement 2 - We are currently receiving 2/5 points for our regular WAX Technical How To articles. Considering that we have provided metrics on our popular Medium viewership and how often they are clearly being utilised in the WAX community would it be possible to increase the awarded points?

Thank-you

**Comment by kaefergeneral** [comment]
Hi Rossco99,

thanks for you appeal. Please find our feedback below:

Engagement 1: We revisited this criteria across several guilds and found some differences in their respective scores for providing Snapshots. This led us to aligning this score over all guilds providing multiple different snapshots and documentation/support. 2 points seemed reasonable to us because as we are seeing an increase in providers.

Engagement 2: After some consideration we decided to increase your score.

Sincerly,
your OIG
