### ISSUE TITLE
Defibox - September Appeal

### ISSUE THREAD

**Issue by DefiboxTeam** [wax-office-of-inspector-general/waxguilds#434]
## Appeal Details

**Guild Name**
Defibox

**Guild Name**

https://wax.defibox.io/

**Issue 1**
Providing test-net history solution (0 or 1): we got 0 points for this. But we are running smoothly for history on testnet, please check: 
https://wax-test.validationcore.io/validations/bp.box

**Issue 2**
About WAX Blindbox system from Defibox, we got only 0.5 points for this product. I think we deserve more. Our community involved got 1000+ accounts partcipated with 2000+ draws. This is for our 2nd Anniversary Event. 
Also for monthly event, the data is also close, which I think is good. We even encourage people to donate their wax to your WAX Guild account Please check it again:

https://wax.defibox.io/scoreShop

Again, thanks for your support to Defibox all the time, we appreciated it very much.

**Comment by kaefergeneral** [comment]
Dear defibox,

please find our appeal feedback below:

Issue 1: There is a slight missunderstanding here. A testnet history solution that could count towards this category would be a full trx history solutions, like a full hyperion node on testnet. Therefore we maintain the 0 points here.


Issue 2: After revisiting the product we didn’t consider adding more points to it, yet. Please keep us updated on the progress and report your monthly DAU and MAU metrics, so that we can reconsider an updated score.

sincerely,
your OIG
