### ISSUE TITLE
WaxMadrid October 2022 Appeal

### ISSUE THREAD

**Issue by EosioMadrid** [wax-office-of-inspector-general/waxguilds#476]
Hi IGs,

first of all, thank you for the review.
I'd like to appeal to recheck the score for the new validator section in waxtracker.io  

I'll summarize what it's been done so far on it.

- A Status Page for all validators and its nodes.

https://wax.eosiotracker.io/statusEndPoints

- Statistical data for each validator, accesible from the Status Page, link available on the the name. Added 7 and 30 days filters. e.g.

https://wax.eosiotracker.io/validatorData/3dkrenderwax

- Current status page for each validator with last validations status. Accesible from the statistics page. e.g.

https://wax.eosiotracker.io/validatorStatus/3dkrenderwax

- Lists of available nodes for each feature:

https://wax.eosiotracker.io/seedEndPoints
https://wax.eosiotracker.io/apiEndPoints
https://wax.eosiotracker.io/v1EndPoints
https://wax.eosiotracker.io/v2EndPoints
https://wax.eosiotracker.io/atomicEndPoints

The stats have been collected for the last 8 days and counting.

All this info is available for testnet as well in:

https://wax-testnet.eosiotracker.io

Thanks again for your work.

**Comment by kaefergeneral** [comment]
Hi EosioMadrid,
when we were evaluating your submission the website was not accessible.
Based on your appeal (8 days and counting) we have to assume the service started after the cut-off date.
As it's working now and we were able actually to evaluate it, we decided to credit you a score for it.
But we have some remarks, as to the usefulness. We recommend implementing aggregated data and a time machine. Otherwise, it provides little value over existing established solutions we have on WAX.

Regards,
your OIG
