### ISSUE TITLE
RATING APPEAL - Token Gamer

### ISSUE THREAD

**Issue by beasteh** [wax-office-of-inspector-general/waxguilds#628]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. Token Gamer App.
We feel that the point decay is unreasonable, we were expecting a point increase... not decrease.

- This is a core product that is in active development. You can see evidence of this by checking the last release date & noticing that we added Polygon support - mentioned in our reports. Whilst unrelated to WAX, obviously this brings lots of eyeballs to WAX as we actively cover WAX news and showcase WAX NFTs within our app.
- We have a new release next week to address a handful of low priority bugs & improve monitoring.
- The antelope upgrade broke our consumer backend which took significant effort to resolve, and is potentially the reason why some may have experienced missing notifications over the past week or 2.
- Decay is relevant to faulty / discontinued products, this app does not reasonably fall into these categories.

2. AA point loss (uptime).
- As per previous issues with validators, they are not always accurate. We have been penalised for AA uptime, which is unfortunately inaccurate. We have logs to support this, which we are happy to provide, example:
zgrep "03/Apr/2023" /var/log/nginx/access.log.22.gz |awk '{print $9}'|sort |uniq -c

241187 status=200
    665 status=204
   3923 status=304
   6235 status=400
 669204 status=404
     10 status=416
  81414 status=429
     95 status=499
    895 status=503

Thank you

**Comment by rakeden** [comment]
Hello @beasteh,

thanks for reaching out! We agreed on the following regarding your appealed points

1. Tokengamer App: We increased the decay target to 2 for now. Please be aware, that we will make adjustments in the future to account for milestones in development, current progress and occasional testing of functionality.

The 2 reasons for the set decay in this evaluation period where:
- When we tested the app, it was not functional as the account data was not feeding.
- Push-Notifications were and are not available for a prolonged time. We consider this a key feature in the score of the Tokengamer app.

At this point we want to clarify on how the decay work with a passage from our guidelines:

_"A successfully released product can be awarded points for a specified period of time until it eventually decays to a minimum threshold for as long as it's maintained and maintenance is reported upon. Decay can be offset by ongoing feature releases and development. Products that stall or die will not earn points. Whether a project has stalled or died will be judged based on the quality of monthly updates (and therein contained metrics) regarding the product."_


2. AA API: From 18th march until the cur-off date of 15th of April we recognise your AA API being reachable, but however was lagging behind a substantial amount of blocks, which renders it unusable. Therefore the AA API has not enough uptime to score 1 point.

Please reference to this sentence from our guidelines: ["A node is considered down if it is missing a significant number of blocks, beyond being a partial node, or if it is lagging."](https://www.notion.so/wax-oig/v4-9-Office-of-Inspector-General-Guidelines-021957e7bf89425798fa2b5801edceea)

---

Feel free to arrange a call and discuss your products in detail with the OIG.


Thank you

**Comment by beasteh** [comment]
Thanks @rakeden, regarding AA - perhaps I haven't explained the issue properly. We're showing as 64% average uptime here: https://wax.validationcore.io/stats/guild/tokengamerio. This is incorrect, and I want to make sure that this source will not be used to determine our AA uptime at the next technical review.

Cheers

**Comment by kaefergeneral** [comment]
@beasteh we cross reference all validations. If one shows reduced average uptime, we fall back to the next.
If guilds see inconsistencies in their validation we ask them to engage with the validation provider and notify us about it with what exactly is off in your opinion. We are not enriely sure what you are appealing in this case, as the reduced uptime is confirmed by both sentnl, validationcore and our manual checks. With tools.ledgerwise.io not being able to check your infrastructure at all. If we check the individual validations, the reason for your reduced uptime was always due to missing blocks. 
And missing a significant amount of blocks, as explained, is always considered as downtime. No matter if the service is otherwise reachable. So from our point of view, the 64% average uptime does seem correct. 
It also does fall in line with the uptime on sentnl:
https://oig.sentnl.io/guilds/tokengamerio

As far as we can tell your issues started on the 19th of march and ended on the 14th of April. So no, this would not impact the coming technical evaluation.

**Comment by beasteh** [comment]
@kaefergeneral  - that one was more of a request for clarity than a point appeal, all clear now.

Thank you
