### ISSUE TITLE
RATING APPEAL - Token Gamer

### ISSUE THREAD

**Issue by beasteh** [wax-office-of-inspector-general/waxguilds#719]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. IPFS is working
2. SSL cert issues will be fixed as soon as our provider reissues the certificate. ETA <24 hours.

Thank you

**Comment by kaefergeneral** [comment]
Dear Token Gamers,
Unfortunately, your IPFS is not being validated by any validation service.
First due to your certificate issue, now because tools.ledgerwise.io is being blocked from validating your infrastructure.
We can not score what is not actively validated.
Furthermore, when we performed our manual checks of your IPFS, it would not load any data.
This extended to the tokengamer app where no images would load, as we assume it is also using your IPFS endpoint.
Given that there is no record of a working IPFS endpoint for the evaluation timeframe, and the service was down when we conducted our manual checks, we do not see us able to grant you a score for providing said IPFS endpoint.

Best,
your OIG
