### ISSUE TITLE
Sentnlagents - RATING APPEAL

### ISSUE THREAD

**Issue by ankh2054** [wax-office-of-inspector-general/waxguilds#848]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. Sengine OIG Portal .

Product has been updated multiple times this year:

- Complete Frontend overhaul.
- Missing block data for both main net and testnet, including graphs.
-  Guilds can request a quick manual scan to ensure their products are working according to our tools. Which is very useful when you resolve a issue and want a quick check.
-  Links to notion from each guilds page.
-  Pulling last months tech score from chain. 
- Last month we wrote a python tool to serialise and deserialise  data so we now properly  test P2P connections.

However our product has consistently been degraded.

3. Atomic API - We have not been scored for our Atomic API.

Thank you
Charles

**Comment by kaefergeneral** [comment]
Hello Charles,

We do recognize the improvements to the OIG Portal. The decay that is currently applied is based on our use and usefulness. Recently, there have been significant issues with the evaluation that led to us being required to grant potentially erroneous scores based on the OIG portal evaluation, while at the same time, in other instances, not being able to rely on the validation due to false negatives.

As we highlighted a while ago, the transparency of the validations is an issue as we can not verify why some checks are passing green on sengine while they fail on all other validators. We will revisit this as the situation improves.

We plan to start a working group in the very near future to streamline validations and validation requirements across validation services. We hope this will help to improve the situation for everyone involved and improve the clarity of evaluations.

As for the atomic assets API, we are sorry for the confusion. With the migration to the new table, it has accidentally been credited in the wrong row.

kind regards,
your OIG

**Comment by ankh2054** [comment]
Thanks for the clarification. I would be good to perhaps have a call to understand how I can improve sengine to ensure the decaying ceases and the score improves.

also one more thing to highlight is I usually also get a score for vuln.sentnl.io as a useful API. Does this still fall under a category?
