### ISSUE TITLE
Wax Galaxy (greeneosiobp) appeal - September evaluation

### ISSUE THREAD

**Issue by sukeshtedla** [wax-office-of-inspector-general/waxguilds#99]
Hi Guys,

We want to appeal three points:

1. Our round availability is more than 99.95% as you can see below and we are still awarded 0 points. **So we would like to appeal Round Availability points.**
![image](https://user-images.githubusercontent.com/15923938/135062549-b422d4f0-a662-4f7a-9974-49ff403e514d.png)
 
2. We offer V1 History and have been doing that for months now as you can see in previous evaluations too. We didn't realise we have to add it explicitly in the bp.json as V1 History is provided by Hyperion. But we have now updated it! Even though it wasn't there we have been serving requests. **So we would like to appeal the V1 History points.**

3. Also during the last month, we helped maintain the testnet by helping EOSArabia, Dublin with their nodes as they were missing blocks/rounds. In addition, we have also upgraded our nodes to v2.0.13 and made sure everything is normal. **So we would like to appeal the testnet participation points.**

Finally, we are just wondering if there were any additional criteria about the "second monthly bonus 'requirement'" as no one was awarded these points. We tried providing our rate limits information but not sure if you are expecting anything more.

**Comment by rakeden** [comment]
Hi Sukesh, 

thanks for the appeal. Here's our feedback.

1. We are granting 1 point for availability. For the second point you would've needed availability > 99.99%

2. We can only monitor and check it when it's in your valid bp.json. That's why we can't grant points this month.

3. We didn't give any points for testnet participation this month, so we are not granting this request.

We are considering to put submitting the rate limits into a new requirement for next month. This month we are not granting any points for submitting the rate limits, but have them prepared for the next month.

**Comment by rakeden** [comment]
Hi Sukesh,

thanks for the appeal. Here's our feedback.

We are granting 1 point for availability. For the second point you would've needed availability > 99.99%

We can only monitor and check it when it's in your valid bp.json. That's why we can't grant points this month.

We didn't give any points for testnet participation this month, so we are not granting this request.

We are considering to put submitting the rate limits into a new requirement for next month. This month we are not granting any points for submitting the rate limits, but have them prepared for the next month.

**Comment by sukeshtedla** [comment]
Hi, regarding point 2, I really don't understand, if you are awarding the points for Hyperion v2 then it basically confirms that V1 history is working as well. 

This point could get us into top-21. We would really appreciate if you reconsider your decision.

**Comment by kaefergeneral** [comment]
v1 points are granted for providing v1 history independent from Hyperion.
As it's supposed to be different services v2 running does not confirm v1 being operational.
Other than that in general points are only granted for features provided in the bp.json.
Aside from not being monitored/verifiable, an endpoint that is not publicly known to exist does not provide value to the ecosystem, and as such does not credit points. 

The same applies to guilds maintaining v2 endpoints that are not announced in their bp.json.
Points are always only credited for services that are made known publicly through the bp.json.

**Comment by sukeshtedla** [comment]
If that's the case most of the top-21 who are awarded points for this in the current evaluation list are providing v1 history servers? I really doubt that. 

How do you even differentiate between the two!

I understand your point that it's not published and can't be used but I can show our logs, we have been serving v1 requests.

![image](https://user-images.githubusercontent.com/15923938/135496066-4c23d9d3-72bf-44d2-99d0-8c198fa8c16c.png)

**Comment by kaefergeneral** [comment]
It does not matter if you are serving requests. If you provide a service we would expect that you are, same as other guilds that provide not publicly known v2 or v1 endpoints.

An endpoint that is provided and only made known to a selected few people will (at least currently) not credit points, the same goes for endpoints that are not listed in the bp.json.

If a guild is announcing v1 but only operating a v2 Hyperion it's their own risk as it means they will lose points for both if there are issues. Until not so long ago it did make a difference if you are running v1 native or within v2.
With the latest updates, this might have changed and be up for a review, but all this does not matter in your case.
Fact is, v1 was not a listed feature in your bp.json so it is not evaluated. There are no exceptions to this.
